export const STATUS = {
  COMPLETE: "COMPLETE",
  PENDING: "PENDING",
};

export const TODO_ACTIONS = {
  UPDATE_TASK_STATUS: "UPDATE_COMPLETION_STATE",
  UPDATE_CURRENT_TASK: "UDPATE_CURRENT_TASK",
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK_TITLE: "UPDATE_TASK_TITLE",
  UPDATE_TASK_DESCRIPTION: "UPDATE_TASK_DESCRIPTION",
};
